# This is a basic workflow to help you get started with Actions

name: CI with Java and Gradle
# controls when the action will run
on: [push]
	build:
	  runs on: ubuntu-latest
	  steps:
	    - name: Setup JDK 11
	      uses: actions/setup-java@v2
	      with:
    java-version: 11
		distribution: adopt
	   
     - name:
	     uses: actions/setup-java@v2
	   - name: Make gradle executable
	      run: chmod +x ./gradlew
	   - name: Build with Gradle
	      run: ./gradlew build
  
